### ISSUE TITLE
low model resolution for inland sea

### ISSUE THREAD

**Issue by hmorzaria** [Fish-MIP/FishMIP_Input_Explorer#8]
For our Atlantis model for Puget Sound, our problem is that the GFDL-MOM6-COBALT2 model appears to have low resolution for Puget Sound and the Salish Sea. I don't think we can force the model with such little data.
![FishMip_data_explorer](https://github.com/user-attachments/assets/9ce9c667-343f-46f4-b768-7dc1da365b84)
We have previously used CNRM-CM6-1-HR and GFDL-CM4, which have better resolution

**Comment by hmorzaria** [comment]
![image](https://github.com/user-attachments/assets/b71d4858-f4ca-4cc5-b765-b44cf08fff54)

**Comment by hmorzaria** [comment]
![image](https://github.com/user-attachments/assets/c10be868-0d5c-4526-9b21-3f04c8974ba2)

**Comment by hmorzaria** [comment]
Which we then interpolated to our model extent (Figures from https://iwaponline.com/jwcc/article/13/12/4255/92429/Future-temperature-and-salinity-in-Puget-Sound) 
![image](https://github.com/user-attachments/assets/0505df8d-6c2b-486a-bc5b-fb755d52b7cd)

**Comment by lidefi87** [comment]
Hi @hmorzaria. 

Thanks for reaching out. The horizontal resolution for the GFDL-MOM6-COBALT2 model is the same globally, 0.25°. Coastal areas may not be well represented due to the model resolution.

The shiny app shows data as it is originally available in the model. Below you can find a quick plot of the raw model data centered in your area of interest, which shows all data available (colored grid cells) and the location of the land mask (white areas). Note that the northernmost grid cell is not included in the shiny because the centroid of the grid cell falls outside your model boundaries.

![image](https://github.com/user-attachments/assets/5d6c452a-ce48-404c-9f74-2f867abbd401)

I am tagging @juliablanchard and @kortegac to this conversation as they may be able to advise what would be the next best steps for your model.

**Comment by kortegac** [comment]
Hi Hem,

Thanks for your message. We first thought that statistical downscaling could address the data issues, but after chatting with some colleagues with expertise in downscaling, they indicated there is not enough data to perform downscaling. As an alternative, Julia suggested you could perform the 3a simulations using your original forcings. Probably derived from GLORYS? We ask all modellers to submit their forcings with their simulations, so this shoulsn't be an issue from our side. Would this be an option for you?

Thanks!

**Comment by lidefi87** [comment]
Hi @hmorzaria. I am closing this issue as it is out of scope here, but if you have any other questions, you can reach out to the regional modelers group.
